//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WellBot.Desktop.Resources {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WellBot.Desktop.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
        public static string WelcomeMessage => ResourceManager.GetString("WelcomeMessage", resourceCulture);
        public static string ChooseAvatar => ResourceManager.GetString("ChooseAvatar", resourceCulture);
        public static string IUnderstand => ResourceManager.GetString("IUnderstand", resourceCulture);
        public static string MenuOpenDashboard => ResourceManager.GetString("MenuOpenDashboard", resourceCulture);
        public static string MenuSettings => ResourceManager.GetString("MenuSettings", resourceCulture);
        public static string MenuChangeAvatar => ResourceManager.GetString("MenuChangeAvatar", resourceCulture);
        public static string MenuDnd => ResourceManager.GetString("MenuDnd", resourceCulture);
        public static string MenuQuit => ResourceManager.GetString("MenuQuit", resourceCulture);
        public static string TrayTooltip => ResourceManager.GetString("TrayTooltip", resourceCulture);
        public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", resourceCulture);
        public static string SettingsGeneral => ResourceManager.GetString("SettingsGeneral", resourceCulture);
        public static string SettingsUserName => ResourceManager.GetString("SettingsUserName", resourceCulture);
        public static string SettingsLanguage => ResourceManager.GetString("SettingsLanguage", resourceCulture);
        public static string SettingsAnimations => ResourceManager.GetString("SettingsAnimations", resourceCulture);
        public static string SettingsStretchScale => ResourceManager.GetString("SettingsStretchScale", resourceCulture);
        public static string SettingsActiveBreakScale => ResourceManager.GetString("SettingsActiveBreakScale", resourceCulture);
        public static string SettingsStartDelay => ResourceManager.GetString("SettingsStartDelay", resourceCulture);
        public static string SettingsOverrideServer => ResourceManager.GetString("SettingsOverrideServer", resourceCulture);
        public static string SettingsCancel => ResourceManager.GetString("SettingsCancel", resourceCulture);
        public static string SettingsSave => ResourceManager.GetString("SettingsSave", resourceCulture);
        public static string AvatarWelcome => ResourceManager.GetString("AvatarWelcome", resourceCulture);
        public static string AvatarSubWelcome => ResourceManager.GetString("AvatarSubWelcome", resourceCulture);
        public static string AvatarStartConfig => ResourceManager.GetString("AvatarStartConfig", resourceCulture);
        public static string AvatarHello => ResourceManager.GetString("AvatarHello", resourceCulture);
        public static string AvatarLetsCustomize => ResourceManager.GetString("AvatarLetsCustomize", resourceCulture);
        public static string AvatarNameQuestion => ResourceManager.GetString("AvatarNameQuestion", resourceCulture);
        public static string AvatarChoose => ResourceManager.GetString("AvatarChoose", resourceCulture);
        public static string AvatarLetsGo => ResourceManager.GetString("AvatarLetsGo", resourceCulture);
        public static string SettingsServerConn => ResourceManager.GetString("SettingsServerConn", resourceCulture);
        public static string SettingsServerUrl => ResourceManager.GetString("SettingsServerUrl", resourceCulture);
        public static string SettingsSchedules => ResourceManager.GetString("SettingsSchedules", resourceCulture);
        public static string SettingsScheduleServerInfo => ResourceManager.GetString("SettingsScheduleServerInfo", resourceCulture);
        public static string SettingsAccessibility => ResourceManager.GetString("SettingsAccessibility", resourceCulture);
        public static string SettingsTtsEnabled => ResourceManager.GetString("SettingsTtsEnabled", resourceCulture);
        public static string StatusConnected => ResourceManager.GetString("StatusConnected", resourceCulture);
        public static string StatusOffline => ResourceManager.GetString("StatusOffline", resourceCulture);
        public static string StatusDetails => ResourceManager.GetString("StatusDetails", resourceCulture);
        public static string SchedHydration => ResourceManager.GetString("SchedHydration", resourceCulture);
        public static string SchedVisual => ResourceManager.GetString("SchedVisual", resourceCulture);
        public static string SchedStretch => ResourceManager.GetString("SchedStretch", resourceCulture);
        public static string SchedActive => ResourceManager.GetString("SchedActive", resourceCulture);
        public static string SchedBreathing => ResourceManager.GetString("SchedBreathing", resourceCulture);
        public static string SchedHealth => ResourceManager.GetString("SchedHealth", resourceCulture);
        public static string SchedUnitMin => ResourceManager.GetString("SchedUnitMin", resourceCulture);
        public static string SettingsWorkHours => ResourceManager.GetString("SettingsWorkHours", resourceCulture);
        public static string SettingsWorkStartTime => ResourceManager.GetString("SettingsWorkStartTime", resourceCulture);
        public static string SettingsWorkEndTime => ResourceManager.GetString("SettingsWorkEndTime", resourceCulture);
        public static string SettingsWorkDays => ResourceManager.GetString("SettingsWorkDays", resourceCulture);
        public static string DaySun => ResourceManager.GetString("DaySun", resourceCulture);
        public static string DayMon => ResourceManager.GetString("DayMon", resourceCulture);
        public static string DayTue => ResourceManager.GetString("DayTue", resourceCulture);
        public static string DayWed => ResourceManager.GetString("DayWed", resourceCulture);
        public static string DayThu => ResourceManager.GetString("DayThu", resourceCulture);
        public static string DayFri => ResourceManager.GetString("DayFri", resourceCulture);
        public static string DaySat => ResourceManager.GetString("DaySat", resourceCulture);
        public static string InvalidTimeFormat => ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
    }
}
